insert into asignatura values('IS-311','IS','Circuitos Electricos','3');
insert into asignatura values('IS-511','IS','Redes de Datos 1','5');
insert into asignatura values('IS-512','IS','Sistemas Operativos 2','5');
insert into asignatura values('IS-501','IS','Bases de Datos 1','5');
insert into asignatura values('IS-411','IS','Electronica','3');
insert into asignatura values('IS-210','IS','Programacion 2','5');
insert into asignatura values('MM-314','IS','Programacion 1','5');
insert into asignatura values('CDE-022','CD','Etica General','3');
insert into asignatura values('CDE-032','CD','Logica Juridica','3');
insert into asignatura values('CDE-042','CD','Interpretacion Juridica','3');
insert into asignatura values('CDE-053','CD','Derecho Romano','4');
insert into asignatura values('CDE-084','CD','Derecho de Familia','4');
insert into asignatura values('CDE-115','CD','Derecho Penal 1','4');
insert into asignatura values('CDE-104','CD','Derecho Penal II','4');
insert into asignatura values('CE040','CA','Microeconomia','3');
insert into asignatura values('CF035','CA','Contabilidad II','4');
insert into asignatura values('CE075','CA','Macroeconomia','4');
insert into asignatura values('AGE378','CA','Administracion Tributaria','4');
insert into asignatura values('AGE398','CA','Gestion por Procesos','4');
insert into asignatura values('AGE102','CA','Administracion','4');